image: node:14-alpine

variables:
  GCP_PROJECT_ID: $PROJECT_ID

before_script:
  - apk add --no-cache --virtual .gyp python make g++ coreutils curl
  - curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
  - mkdir -p /usr/local/gcloud
  - tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz
  - /usr/local/gcloud/google-cloud-sdk/install.sh
  - export PATH=$PATH:/usr/local/gcloud/google-cloud-sdk/bin

build_staging:
  stage: build
  environment: Staging
  only:
    - staging
  variables:
    NODE_ENV: staging
  script:
    - npm install --production --progress=false
    - npm run build
  artifacts:
    paths:
      - .nuxt

build_production:
  stage: build
  environment: Production
  only:
    - production
  variables:
    NODE_ENV: production
  script:
    - npm install --production --progress=false
    - npm run build
  artifacts:
    paths:
      - .nuxt

deploy_staging:
  stage: deploy
  environment: Staging
  only:
    - staging
  script:
    - node generateKeyfile.js "$(echo $PRIVATE_KEY | base32 -d)" > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.staging.yaml

deploy_production:
  stage: deploy
  environment: Production
  only:
    - production
  script:
    - node generateKeyfile.js "$(echo $PRIVATE_KEY | base32 -d)" > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.production.yaml
